version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        SENTRY_RELEASE: local-dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SENTRY_DSN=${SENTRY_DSN}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sampleapp_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
